// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnLaYxHsa6Je8oTxmSQf_oE3l5hPUozaQ',
    appId: '1:1084638783701:web:ac5a33b119c27a0bd35a5c',
    messagingSenderId: '1084638783701',
    projectId: 'fpsprosettings',
    authDomain: 'fpsprosettings.firebaseapp.com',
    storageBucket: 'fpsprosettings.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR9QDfq38y-Ys9s9C6uTn1b8lq9SeLUvk',
    appId: '1:1084638783701:android:0fa52adf87a849a8d35a5c',
    messagingSenderId: '1084638783701',
    projectId: 'fpsprosettings',
    storageBucket: 'fpsprosettings.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmd_FAiBs4ySEIZnepN0ZU2Eajub3OAG8',
    appId: '1:1084638783701:ios:0ff4bf9bcbeb9c8ad35a5c',
    messagingSenderId: '1084638783701',
    projectId: 'fpsprosettings',
    storageBucket: 'fpsprosettings.firebasestorage.app',
    iosBundleId: 'com.example.fpsprosettings',
  );
}
